apiVersion: v1
kind: Service
metadata:
  name: tunnel-service
  namespace: applications
spec:
  type: ClusterIP
  selector:
    app: tunnel
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
