apiVersion: v1
kind: Service
metadata:
  name: fleetstorm-landing-service
spec:
  type: ClusterIP
  selector:
    app: fleetstorm-landing
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
