apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetstorm-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetstorm-ui
  template:
    metadata:
      labels:
        app: fleetstorm-ui
    spec:
      containers:
        - name: fleetstorm-ui
          image: ekalkutin/fleetstorm-ui:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
