# kubectl create secret tls kalkutin-dev-tls-secret --cert=fullchain.crt --key=kalkutin.dev.key -n applications

apiVersion: v1
kind: Secret
metadata:
  name: kalkutin-dev-tls-secret
  namespace: applications
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""