apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce # Allows the volume to be mounted as read-write by a single node
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
