# portainer/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa
  namespace: applications
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer-cr
  namespace: applications
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-crb
  namespace: applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portainer-cr
subjects:
- kind: ServiceAccount
  name: portainer-sa
  namespace: applications
