# portainer/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa
  namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer-cr
  namespace: infrastructure
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-crb
  namespace: infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portainer-cr
subjects:
  - kind: ServiceAccount
    name: portainer-sa
    namespace: infrastructure
