apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
