apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetstorm-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetstorm-core
  template:
    metadata:
      labels:
        app: fleetstorm-core
    spec:
      containers:
        - name: fleetstorm-core
          image: ekalkutin/fleetstorm-core:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
