apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-lance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x-lance
  template:
    metadata:
      labels:
        app: x-lance
    spec:
      containers:
        - name: x-lance
          image: ekalkutin/x-lance:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
