# apps/resume/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-prod

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: core-deployment-patch.yaml
  - path: ui-deployment-patch.yaml
  - path: landing-deployment-patch.yaml
